name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Cache SBT dependencies
      uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          restore-keys: ${{ runner.os }}-sbt
    - name: Run tests
      run: sbt test


        - uses: actions/cache@v1
          with:
            path: ~/.ivy2
            key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
        - uses: actions/cache@v1
          with:
            path: ~/.sbt
            key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.properties') }}
